/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddImagePanel.java
 *
 * Created on 2011-mar-25, 18:49:20
 */

package edu.chalmers.platypus.view.gui;

import java.awt.Cursor;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;

/**
 *
 * @author skoldator
 */
public class AddImagePanel extends JPanel {

    /** Creates new form AddImagePanel */
    private AddImagePanel() {
        initComponents();
    }
    public AddImagePanel(BatchThumbPanel listToAddTo) {
        this();
        this.listToAddTo = listToAddTo;
    }


    /** 
     *  Below: autogenerated NetBeans code
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadOverlayLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AddImagePanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadOverlayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadOverlayLabel.setIcon(resourceMap.getIcon("loadOverlayLabel.icon")); // NOI18N
        loadOverlayLabel.setText(resourceMap.getString("loadOverlayLabel.text")); // NOI18N
        loadOverlayLabel.setName("loadOverlayLabel"); // NOI18N
        add(loadOverlayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));
        loadOverlayLabel.setVisible(false);

        addButton.setBackground(resourceMap.getColor("addButton.background")); // NOI18N
        addButton.setFont(resourceMap.getFont("addButton.font")); // NOI18N
        addButton.setIcon(resourceMap.getIcon("addButton.icon")); // NOI18N
        addButton.setText(resourceMap.getString("addButton.text")); // NOI18N
        addButton.setContentAreaFilled(false);
        addButton.setFocusable(false);
        addButton.setName("addButton"); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(ActionEvent evt) {
        listToAddTo.openFileChooser();
    }

    public void setEnabled() {
        loadOverlayLabel.setVisible(false);
        addButton.setEnabled(true);
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    public void setDisabled() {
        addButton.setEnabled(false);
        loadOverlayLabel.setVisible(true);
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel loadOverlayLabel;
    // End of variables declaration//GEN-END:variables
	
    private BatchThumbPanel listToAddTo;
}
