/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImagePreviewPanel.java
 *
 * Created on 2011-apr-01, 19:41:46
 */

package edu.chalmers.platypus.view.gui;

import edu.chalmers.platypus.util.Locator;

import javax.swing.ImageIcon;

/**
 *
 * @author skoldator
 */
public class ImagePreviewPanel extends javax.swing.JPanel {

    /** Creates new form ImagePreviewPanel */
    public ImagePreviewPanel() {
        initComponents();
    }
    public void setImage(ImageIcon img) {
        image = img;
        updateImage();
    }
    public void engageWaitState() {
        previewLabel.setEnabled(false);
    }
    public void updateImage() {
        previewLabel.setEnabled(true);
        previewLabel.setIcon(image);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previewLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        previewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ImagePreviewPanel.class);
        previewLabel.setIcon(resourceMap.getIcon("previewLabel.icon")); // NOI18N
        previewLabel.setText(resourceMap.getString("previewLabel.text")); // NOI18N
        previewLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        previewLabel.setDisabledIcon(resourceMap.getIcon("previewLabel.disabledIcon")); // NOI18N
        previewLabel.setName("previewLabel"); // NOI18N
        previewLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(previewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(previewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel previewLabel;
    // End of variables declaration//GEN-END:variables

    private ImageIcon image;
}
