package edu.chalmers.platypus.util;

/**
 * Labels for possible changes in state in model. Used to communicate to the GUI
 * when the model has changed.
 */
public enum StateChanges {
    NEW_FILTER_ADDED_TO_BATCH, FILTER_REMOVED_FROM_BATCH, NEW_FILTER_ADDED_TO_APPLICATION, FILTER_LOADED, DUPLICATE_FILTER_SELECTED,

    NEW_IMAGE_IN_BATCH, IMAGE_REMOVED_FROM_BATCH, IMAGE_BATCH_EMPTY, IMAGE_BATCH_CLEARED,

    PROCESSING_IMAGE, APPLYING_FILTER, SAVED_IMAGE, SAVE_OPERATION_ABORTED, SAVE_OPERATION_FINISHED,

    NEW_PREVIEW_IMAGE, PREVIEW_IMAGE_UPDATED,

    MODEL_RESET,

    ERROR_OCCURED
}
