/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddImagePanel.java
 *
 * Created on 2011-mar-25, 18:49:20
 */

package edu.chalmers.platypus.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

/**
 *
 * @author skoldator
 */
public class AddImagePanel extends JPanel {

    /** Creates new form AddImagePanel */
    private AddImagePanel() {
        initComponents();
    }
    public AddImagePanel(BrowseViewPanel listToAddTo) {
        this();
        this.listToAddTo = listToAddTo;
    }


    /** 
     *  Below: autogenerated NetBeans code
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jButton1 = new JButton();

        ResourceMap resourceMap = Application.getInstance(PlatypusApp.class).getContext().getResourceMap(AddImagePanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jButton1.setBackground(resourceMap.getColor("jButton1.background")); // NOI18N
        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        );
    }

    private void jButton1ActionPerformed(ActionEvent evt) {
        listToAddTo.openFileChooser();
    }

    private JButton jButton1;
    private BrowseViewPanel listToAddTo;
}
