/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThumbnailImage.java
 *
 * Created on 2011-mar-24, 20:34:20
 */

package edu.chalmers.platypus.view;

import java.awt.Point;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import edu.chalmers.platypus.model.BatchImage;

/**
 *
 * @author skoldator
 */
public class ThumbnailImage extends javax.swing.JPanel {

    private ThumbnailImage() {
    }
    
    public ThumbnailImage(BatchImage img) {
        initComponents();
        jLabel2.setText(img.getFileName());
        jLabel1.setIcon(img.getThumbnail());
    }
    
    public void showControls(){
        jButton1.setVisible(true);
        jLabel2.setVisible(true);
    }

    public void hideControls(){
        jButton1.setVisible(false);
        jLabel2.setVisible(false);
    }
    
    private void formMouseEntered(java.awt.event.MouseEvent evt) {
        showControls();
    }

    private void formMouseExited(java.awt.event.MouseEvent evt) {
        Point mousePoint = evt.getLocationOnScreen();
        Point panelPoint = jPanel1.getLocationOnScreen();
        if (panelPoint.x+jPanel1.getWidth() <= mousePoint.x ||
                panelPoint.x >= mousePoint.x || panelPoint.y+jPanel1.getHeight() <=
                mousePoint.y || panelPoint.y >= mousePoint.y) {
            hideControls();
        }
    }
    /** 
     *  Below: All autogenerated NetBeans code
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPanel1 = new JPanel();
        jButton1 = new JButton();
        jLabel2 = new JLabel();
        jLabel1 = new JLabel();

        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.chalmers.platypus.view.PlatypusApp.class).getContext().getResourceMap(ThumbnailImage.class);
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setRequestFocusEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jButton1);
        jButton1.setBounds(96, 0, 24, 24);
        jButton1.setVisible(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 70, 120, 20);
        jLabel2.setVisible(false);

        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 120, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }

    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
}
