/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageBrowserPanel.java
 *
 * Created on 2011-mar-24, 20:30:14
 */

package edu.chalmers.platypus.view.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

import org.jdesktop.application.ResourceMap;

import edu.chalmers.platypus.ComBus;
import edu.chalmers.platypus.Locator;
import edu.chalmers.platypus.model.BatchImage;
import edu.chalmers.platypus.util.StateChanges;

/**
 *
 * @author skoldator
 */
public class BrowseViewPanel extends javax.swing.JPanel implements PropertyChangeListener {

    /** Creates new form ImageBrowserPanel */
    public BrowseViewPanel() {
        initComponents();

        addPanel(addImageButton);
        ComBus.subscribe(this);
    }

    public BrowseViewPanel(PlatypusView parent) {
        this();
        this.parent = parent;
    }

    private void addPanel(JPanel addToList) {
        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout());
        panel.add(addToList);
        panel.setOpaque(true);
        jPanel1.add(addToList);
        jPanel1.revalidate();
    }
    private void removePanel(BatchImage img) {
    	for (Component c : jPanel1.getComponents()) {
    		if (c instanceof ThumbnailImage) {
    			if (((ThumbnailImage)c).getBatchImage() == img) {
    				jPanel1.remove(c);
    				jPanel1.revalidate();
    				jPanel1.repaint();
    			}
    		}
    	}
    }

    public void setButtonNext() {
        ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.chalmers.platypus.view.gui.PlatypusApp.class).getContext().getResourceMap(BrowseViewPanel.class);
        jButton1.setText(resourceMap.getString("jButton1.alttext"));
    }
    
    public void setButtonAdd() {
        ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.chalmers.platypus.view.gui.PlatypusApp.class).getContext().getResourceMap(BrowseViewPanel.class);
        jButton1.setText(resourceMap.getString("jButton1.text"));
    }
    
	@Override
	public void propertyChange(PropertyChangeEvent evt) {
		String change = evt.getPropertyName();
		if (change.equals(StateChanges.NEW_IMAGE_IN_BATCH.toString())) {
			BatchImage addedImage = (BatchImage)evt.getNewValue();
			addPanel(new ThumbnailImage(addedImage, this));
		} 
		else if (change.equals(StateChanges.IMAGE_REMOVED_FROM_BATCH.toString())) {
			BatchImage removedImage = (BatchImage)evt.getOldValue();
			removePanel(removedImage);
		} else if (change.equals(StateChanges.NEW_PREVIEW_IMAGE.toString())) {
			ImageIcon newPreview = (ImageIcon)evt.getNewValue();
			parent.setPreview(newPreview);
		}
	}
	
    public void openFileChooser() {
        JFileChooser browser = new JFileChooser();
        browser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileFilter filter = new FileNameExtensionFilter("Supported pictures " +
                "(*.jpg, *.png, *.gif)",
                "jpeg","JPEG","JPG","jpg","png","PNG","gif","GIF");
        browser.setFileFilter(filter);
        browser.setAcceptAllFileFilterUsed(false);
        browser.setMultiSelectionEnabled(true);
        int result = browser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            for (File f : browser.getSelectedFiles()) {
            	parent.getGUICtrl().addImageToBatch(f);
            }
        }
    }
    
    public void setPreview(ThumbnailImage img) {
    	for (Component c : jPanel1.getComponents()) {
    		if (c instanceof ThumbnailImage) {
    			ThumbnailImage thumb = (ThumbnailImage)c;
    			if (thumb != img) {
    				thumb.deselectAsPreview();
    			}
    		}
    	}
    	// TODO call ctrl to set preview
    }
    
    /** 
     *  Below: autogenerated NetBeans code
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.chalmers.platypus.view.gui.PlatypusApp.class).getContext().getResourceMap(BrowseViewPanel.class);
        setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("Form.border.title"))); // NOI18N
        setName("Form"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(resourceMap.getColor("jScrollPane1.background")); // NOI18N
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);
        WrapLayout l = new WrapLayout();
        l.setAlignment(WrapLayout.LEFT);
        jPanel1.setLayout(l);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jScrollPane1.getViewport().setBackground(Color.WHITE);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	if (parent != null) {
        	if (parent.numberOfFilterPanels() == 0) {
            	parent.showAddFilterDialog();
        	}
        	if (parent.numberOfFilterPanels() > 0) {
                parent.showNextView();
        	}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (parent != null) {
            parent.showLoadPresetDialog();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private final AddImagePanel addImageButton = new AddImagePanel(this);
    private PlatypusView parent;
}
