/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageBrowserPanel.java
 *
 * Created on 2011-mar-24, 20:30:14
 */

package edu.chalmers.platypus.view;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.net.MalformedURLException;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.ScrollPaneConstants;

import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;

import edu.chalmers.platypus.Locator;
import edu.chalmers.platypus.model.BatchImage;
import edu.chalmers.platypus.view.resources.StateChanges;

/**
 *
 * @author skoldator
 */
public class BrowseViewPanel extends javax.swing.JPanel implements PropertyChangeListener {

    /** Creates new form ImageBrowserPanel */
    public BrowseViewPanel() {
        initComponents();

        addPanel(addImageButton);
        Locator.getCtrl().subscribeAsModelListener(this);
    }

    public BrowseViewPanel(PlatypusView parent) {
        this();
        this.parent = parent;
    }

    private void addPanel(JPanel addToList) {
        JPanel panel = new JPanel();
        panel.setLayout(new FlowLayout());
        panel.add(addToList);
        panel.setOpaque(true);
        jPanel1.add(addToList);
        jPanel1.revalidate();
    }
    
	@Override
	public void propertyChange(PropertyChangeEvent evt) {
		String change = evt.getPropertyName();
		if (change.equals(StateChanges.NEW_IMAGE_IN_BATCH.toString())) {
			BatchImage addedImage = (BatchImage)evt.getNewValue();
			addPanel(new ThumbnailImage(addedImage));
		}
	}
	
    public void openFileChooser() {
        JFileChooser browser = new JFileChooser();
        browser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        browser.setMultiSelectionEnabled(true);
        int result = browser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            for (File f : browser.getSelectedFiles()) {
            	Locator.getCtrl().addImageToBatch(f);
            }
        }
    }
    /** 
     *  Below: autogenerated NetBeans code
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jButton1 = new JButton();
        jScrollPane1 = new JScrollPane();
        jPanel1 = new JPanel();
        jButton2 = new JButton();

        ResourceMap resourceMap = Application.getInstance(PlatypusApp.class).getContext().getResourceMap(BrowseViewPanel.class);
        setBorder(BorderFactory.createTitledBorder(resourceMap.getString("Form.border.title"))); // NOI18N
        setName("Form"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(resourceMap.getColor("jScrollPane1.background")); // NOI18N
        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);
        WrapLayout l = new WrapLayout();
        l.setAlignment(WrapLayout.LEFT);
        jPanel1.setLayout(l);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        jScrollPane1.getViewport().setBackground(Color.WHITE);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (parent != null) {
            parent.switchToView();
        }
    }


    private JButton jButton1;
    private JButton jButton2;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;

    private final AddImagePanel addImageButton = new AddImagePanel(this);
    private PlatypusView parent;
}
