/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilterViewPanel.java
 *
 * Created on 2011-apr-01, 18:24:29
 */

package edu.chalmers.platypus.view;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;


import edu.chalmers.platypus.model.IFilter;
import edu.chalmers.platypus.util.ComBus;
import edu.chalmers.platypus.util.StateChanges;
import edu.chalmers.platypus.view.gui.FilterPanel;
import edu.chalmers.platypus.view.gui.PlatypusView;

/**
 *
 * @author skoldator
 */
public class FilterViewPanel extends javax.swing.JPanel implements PropertyChangeListener {

    /** Creates new form FilterViewPanel */
    public FilterViewPanel() {
        initComponents();
        ComBus.subscribe(this);
    }

    public FilterViewPanel(PlatypusView parent) {
        this();
        this.parent = parent;
    }

    public PlatypusView getMainView() {
        return parent;
    }
    
    public int numberOfActiveFilters() {
    	return addedFilterPanels.size();
    }
    
    public void addFilterPanel(IFilter filter) {
    	addedFilterPanels.add(new FilterPanel(filter, this));
    	currentPanelIndex++;
    	updateFilterPanels();
    	showFilterPanel(addedFilterPanels.get(addedFilterPanels.size()-1));
    	parent.setBrowseButtonNext();
    }
    
    public void removeFilterPanel(IFilter filter) {
    	for (int i = 0; i < addedFilterPanels.size(); i++) {
    		if (addedFilterPanels.get(i).getFilter() == filter) {
    	    	addedFilterPanels.remove(i);
    			if (addedFilterPanels.size() == 0) {
    				currentPanelIndex = -1;
    				parent.setBrowseButtonAdd();
    				showPreviousFilterPanel();
    			} else {
    				currentPanelIndex = addedFilterPanels.size()-1;
    				showFilterPanel(addedFilterPanels.get(addedFilterPanels.size()-1));
    			}
    	    	updateFilterPanels();
    	    	break;
    		}
    	}
    }
    private void showFilterPanel(FilterPanel panel) {
    	filterViewSplitPane.setRightComponent(panel);
        setDivider();
    	System.out.println("Showing filter: "+(currentPanelIndex+1)+"/"+(addedFilterPanels.size()));
    }
    
    public void showNextFilterPanel() {
    	if (currentPanelIndex+1 < addedFilterPanels.size()) {
        	showFilterPanel(addedFilterPanels.get(++currentPanelIndex));
    	} else {
    		parent.showAddFilterDialog();
    	}
    }
    
    public void showPreviousFilterPanel() {
    	if (currentPanelIndex > 0) {
    		showFilterPanel(addedFilterPanels.get(--currentPanelIndex));
    	} else {
    		parent.showPreviousView();
    	}
    }
    
    private void updateFilterPanels() {
    	for (int i = 0; i <= addedFilterPanels.size()-1; i++) {
            if (i != addedFilterPanels.size()-1) {
                addedFilterPanels.get(i).setAddButtonToNext();
            } else {
                addedFilterPanels.get(i).setAddButtonToAdd();
            }
            addedFilterPanels.get(i).setFilterNumber(i+1, addedFilterPanels.size());
    	}
    }
    
    public void setDivider() {
        if (filterViewSplitPane != null) {
        	filterViewSplitPane.setDividerLocation(0.6);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterViewSplitPane = new javax.swing.JSplitPane();
        previewPanel = new edu.chalmers.platypus.view.gui.PreviewPanel();

        setName("Form"); // NOI18N

        filterViewSplitPane.setDividerLocation(180);
        filterViewSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        filterViewSplitPane.setName("filterViewSplitPane"); // NOI18N
        filterViewSplitPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                filterViewSplitPaneComponentResized(evt);
            }
        });

        previewPanel.setName("previewPanel"); // NOI18N
        filterViewSplitPane.setTopComponent(previewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filterViewSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filterViewSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterViewSplitPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_filterViewSplitPaneComponentResized
    	setDivider();
    }//GEN-LAST:event_filterViewSplitPaneComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane filterViewSplitPane;
    private edu.chalmers.platypus.view.gui.PreviewPanel previewPanel;
    // End of variables declaration//GEN-END:variables

    private PlatypusView parent;
    private ArrayList<FilterPanel> addedFilterPanels = new ArrayList<FilterPanel>();
    private int currentPanelIndex = -1;
    
	@Override
	public void propertyChange(PropertyChangeEvent evt) {
		String change = evt.getPropertyName();
		if (change.equals(StateChanges.NEW_FILTER_ADDED_TO_BATCH.toString())) {
			addFilterPanel((IFilter)evt.getNewValue());
		} else if (change.equals(StateChanges.FILTER_REMOVED_FROM_BATCH.toString())) {
			removeFilterPanel((IFilter)evt.getOldValue());
		} else if (change.equals(StateChanges.MODEL_RESET.toString())) {
                        currentPanelIndex = -1;
			addedFilterPanels.clear();
		}
	}

}
