/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilterViewPanel.java
 *
 * Created on 2011-apr-01, 18:24:29
 */

package edu.chalmers.platypus.view;

/**
 *
 * @author skoldator
 */
public class FilterViewPanel extends javax.swing.JPanel {

    /** Creates new form FilterViewPanel */
    public FilterViewPanel() {
        initComponents();
    }

    public FilterViewPanel(PlatypusView parent) {
        this();
        this.parent = parent;
    }

    public PlatypusView getMainView() {
        return parent;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        previewPanel1 = new edu.chalmers.platypus.view.PreviewPanel();
        filterPanel1 = new edu.chalmers.platypus.view.FilterPanel(this);

        setName("Form"); // NOI18N

        jSplitPane1.setDividerLocation(180);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        previewPanel1.setName("previewPanel1"); // NOI18N
        jSplitPane1.setTopComponent(previewPanel1);

        filterPanel1.setName("filterPanel1"); // NOI18N
        jSplitPane1.setRightComponent(filterPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.chalmers.platypus.view.FilterPanel filterPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private edu.chalmers.platypus.view.PreviewPanel previewPanel1;
    // End of variables declaration//GEN-END:variables

    private PlatypusView parent;

}
