/*
 * PlatypusView.java
 */

package edu.chalmers.platypus.view;

import java.awt.CardLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;

import javax.swing.JDialog;
import javax.swing.JFrame;

import org.jdesktop.application.Action;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;

import edu.chalmers.platypus.model.IFilter;
import edu.chalmers.platypus.view.resources.StateChanges;

/**
 * The application's main frame.
 */
public class PlatypusView extends FrameView implements PropertyChangeListener {

    public PlatypusView(SingleFrameApplication app) {
        super(app);

        initComponents();

        ResourceMap resourceMap = getResourceMap();
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = PlatypusApp.getApplication().getMainFrame();
            aboutBox = new PlatypusAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        PlatypusApp.getApplication().show(aboutBox);
    }

    public void showAddFilterDialog() {
        addFilterDialog = new JDialog(this.getFrame(), "Lägg till filter", true);
        addFilterDialog.add(new AddFilterPanel(addFilterDialog, this));
        addFilterDialog.pack();
        addFilterDialog.setLocationRelativeTo(this.getComponent());
    	addFilterDialog.setVisible(true);
    }

    public void showNextView() {
        ((CardLayout)jPanel1.getLayout()).next(jPanel1);
    }
    public void showPreviousView() {
        ((CardLayout)jPanel1.getLayout()).previous(jPanel1);
    }

    public int numberOfActiveFilters() {
    	return filterViewPanel1.getNumberOfFilterPanels();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        startViewPanel1 = new edu.chalmers.platypus.view.StartViewPanel(this);
        imageBrowserPanel1 = new edu.chalmers.platypus.view.BrowseViewPanel(this);
        filterViewPanel1 = new edu.chalmers.platypus.view.FilterViewPanel(this);
        saveViewPanel1 = new edu.chalmers.platypus.view.SaveViewPanel(this);
        applyViewPanel1 = new edu.chalmers.platypus.view.ApplyViewPanel(this);
        finishedViewPanel1 = new edu.chalmers.platypus.view.FinishedViewPanel(this);
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.CardLayout());

        startViewPanel1.setName("startViewPanel1"); // NOI18N
        jPanel1.add(startViewPanel1, "card7");

        imageBrowserPanel1.setName("imageBrowserPanel1"); // NOI18N
        jPanel1.add(imageBrowserPanel1, "browseViewPanel");

        filterViewPanel1.setName("filterViewPanel1"); // NOI18N
        jPanel1.add(filterViewPanel1, "card4");

        saveViewPanel1.setName("saveViewPanel1"); // NOI18N
        jPanel1.add(saveViewPanel1, "card6");

        applyViewPanel1.setName("applyViewPanel1"); // NOI18N
        jPanel1.add(applyViewPanel1, "card3");

        finishedViewPanel1.setName("finishedViewPanel1"); // NOI18N
        jPanel1.add(finishedViewPanel1, "card5");

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.chalmers.platypus.view.PlatypusApp.class).getContext().getResourceMap(PlatypusView.class);
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(edu.chalmers.platypus.view.PlatypusApp.class).getContext().getActionMap(PlatypusView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        menuBar.setVisible(false);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.chalmers.platypus.view.ApplyViewPanel applyViewPanel1;
    private edu.chalmers.platypus.view.FilterViewPanel filterViewPanel1;
    private edu.chalmers.platypus.view.FinishedViewPanel finishedViewPanel1;
    private edu.chalmers.platypus.view.BrowseViewPanel imageBrowserPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private edu.chalmers.platypus.view.SaveViewPanel saveViewPanel1;
    private edu.chalmers.platypus.view.StartViewPanel startViewPanel1;
    // End of variables declaration//GEN-END:variables


    private JDialog aboutBox;
    private JDialog addFilterDialog;

    public void propertyChange(PropertyChangeEvent evt) {

    }

}
